#!/usr/bin/env node
// brand.json -> fonts + CSS variables injected into index.html (between <!-- brand:start/end -->).
//
//   node brand.mjs <project-dir>
//
// Fonts: each family in brand.json "fonts" is installed from @fontsource (Google Fonts) into
// assets/fonts when missing. Custom fonts: drop <slug>-latin-<weight>-normal.woff2 files there.
// Scenes must use the variables (font-family: var(--font-display)), never a family name, so
// every look works with every brand.
import fs from "node:fs";
import os from "node:os";
import path from "node:path";
import { spawnSync } from "node:child_process";

const dir = path.resolve(process.argv[2] || ".");
const brand = JSON.parse(fs.readFileSync(path.join(dir, "brand.json"), "utf8"));
const fontDir = path.join(dir, "assets", "fonts");
fs.mkdirSync(fontDir, { recursive: true });
const shell = process.platform === "win32";
const warn = [];

// ---------- colour helpers ----------
const rgb = (h) => {
  const n = parseInt(h.replace("#", "").slice(0, 6), 16);
  return [(n >> 16) & 255, (n >> 8) & 255, n & 255];
};
const hex = (c) => "#" + c.map((v) => Math.round(Math.max(0, Math.min(255, v))).toString(16).padStart(2, "0")).join("");
const mix = (a, b, k) => hex(rgb(a).map((v, i) => v + (rgb(b)[i] - v) * k));
const lum = (h) => {
  const [r, g, b] = rgb(h).map((v) => ((v /= 255) <= 0.03928 ? v / 12.92 : ((v + 0.055) / 1.055) ** 2.4));
  return 0.2126 * r + 0.7152 * g + 0.0722 * b;
};

// ---------- fonts ----------
const slug = (f) => f.toLowerCase().replace(/\s+/g, "-");
const roles = Object.assign({ display: "Inter", text: "Inter", mono: "JetBrains Mono" }, brand.fonts || {});
const families = [...new Set(Object.values(roles))];
const faces = [];
for (const fam of families) {
  const s = slug(fam);
  const have = () => fs.readdirSync(fontDir).filter((f) => f.startsWith(`${s}-latin-`) && f.endsWith("-normal.woff2"));
  if (have().length === 0) {
    const tmp = fs.mkdtempSync(path.join(os.tmpdir(), "fontsource-"));
    const r = spawnSync("npm", ["pack", `@fontsource/${s}`, "--silent"], { cwd: tmp, shell, encoding: "utf8" });
    const tgz = fs.readdirSync(tmp).find((f) => f.endsWith(".tgz"));
    if (r.status === 0 && tgz) {
      spawnSync("tar", ["-xzf", tgz], { cwd: tmp });
      const files = path.join(tmp, "package", "files");
      for (const w of [300, 400, 500, 600, 700, 800, 900]) {
        const f = path.join(files, `${s}-latin-${w}-normal.woff2`);
        if (fs.existsSync(f)) fs.copyFileSync(f, path.join(fontDir, path.basename(f)));
      }
      const lic = fs.readdirSync(path.join(tmp, "package")).find((f) => /^LICEN[CS]E/i.test(f));
      if (lic) fs.copyFileSync(path.join(tmp, "package", lic), path.join(fontDir, `LICENSE-${s}.txt`));
    } else warn.push(`"${fam}" is not on @fontsource: add ${s}-latin-<weight>-normal.woff2 files to assets/fonts`);
    fs.rmSync(tmp, { recursive: true, force: true });
  }
  for (const f of have()) {
    const w = f.match(/-latin-(\d{3})-normal/)[1];
    faces.push(`      @font-face { font-family: "${fam}"; font-weight: ${w}; src: url("assets/fonts/${f}") format("woff2"); }`);
  }
}

// ---------- colours ----------
const c = Object.assign({ primary: "#5b5bf6", secondary: "#f472b6", ink: "#0b0b10", paper: "#ffffff" }, brand.colors || {});
const vars = {
  "--brand-primary": c.primary,
  "--brand-secondary": c.secondary,
  "--brand-ink": c.ink,
  "--brand-paper": c.paper,
  "--brand-muted": c.muted || mix(c.ink, c.paper, 0.55),
  "--brand-line": c.line || mix(c.ink, c.paper, 0.86),
  "--brand-primary-soft": mix(c.primary, c.paper, 0.86),
  "--brand-primary-deep": mix(c.primary, c.ink, 0.55),
  "--brand-on-primary": lum(c.primary) > 0.45 ? c.ink : "#ffffff",
  "--font-display": `"${roles.display}", system-ui, sans-serif`,
  "--font-text": `"${roles.text}", system-ui, sans-serif`,
  "--font-mono": `"${roles.mono}", ui-monospace, monospace`,
};
for (const [k, v] of Object.entries(brand.extraColors || {})) vars[`--brand-${k}`] = v;

const block = `<!-- brand:start (generated by scripts/brand.mjs from brand.json; do not edit) -->
    <style>
${faces.join("\n")}
      :root {
${Object.entries(vars).map(([k, v]) => `        ${k}: ${v};`).join("\n")}
      }
    </style>
    <!-- brand:end -->`;

const idx = path.join(dir, "index.html");
let html = fs.readFileSync(idx, "utf8");
if (!/<!-- brand:start[\s\S]*?brand:end -->/.test(html)) {
  console.error("index.html has no <!-- brand:start --> ... <!-- brand:end --> markers in <head>");
  process.exit(1);
}
html = html.replace(/<!-- brand:start[\s\S]*?brand:end -->/, block);
fs.writeFileSync(idx, html);
console.log(`brand: ${brand.name || "?"} · ${families.join(", ")} · primary ${c.primary} · ${faces.length} font faces -> index.html`);
for (const w of warn) console.log("  warn:", w);
